### ISSUE TITLE
原先通过tac获取sign的逻辑似乎失效了？

### ISSUE THREAD

**Issue by zhangchj9** [coder-fly/douyin-signature#12]
response = requests.get('https://www.iesdouyin.com/share/user/58958068057', headers=headers, verify=False)
tac = re.search(r"tac='([\s\S]*?)'</script>", response.text)
此时的tac为None，不知是不是网页的加载方式有所改变？

**Comment by khangpropk123** [comment]
I get the same too :((

**Comment by coder-fly** [comment]
网页版好像不返回数据了，我用手机正常访问也没数据。

**Comment by khangpropk123** [comment]
> 网页版好像不返回数据了，我用手机正常访问也没数据。

I think it change method to genarate _signature. 
Lastnight it was working but now it did'nt :(

**Comment by guinner** [comment]
> response = requests.get('https://www.iesdouyin.com/share/user/58958068057', headers=headers, verify=False)
> tac = re.search(r"tac='([\s\S]*?)'</script>", response.text)
> 此时的tac为None，不知是不是网页的加载方式有所改变？

现在签名应该不需要tac和userid了，签名方法也没变，但并不是每次请求都有数据

**Comment by zhangchj9** [comment]
> > response = requests.get('https://www.iesdouyin.com/share/user/58958068057', headers=headers, verify=False)
> > tac = re.search(r"tac='([\s\S]*?)'</script>", response.text)
> > 此时的tac为None，不知是不是网页的加载方式有所改变？
> 
> 现在签名应该不需要tac和userid了，签名方法也没变，但并不是每次请求都有数据

奇怪的是，手机浏览器直接访问 主题 或者 用户列表 的分享链接都经常加载不出数据

**Comment by guinner** [comment]
> > > response = requests.get('https://www.iesdouyin.com/share/user/58958068057', headers=headers, verify=False)
> > > tac = re.search(r"tac='([\s\S]*?)'</script>", response.text)
> > > 此时的tac为None，不知是不是网页的加载方式有所改变？
> > 
> > 
> > 现在签名应该不需要tac和userid了，签名方法也没变，但并不是每次请求都有数据
> 
> 奇怪的是，手机浏览器直接访问 主题 或者 用户列表 的分享链接都经常加载不出数据

感觉他们是直接限制了这个接口，连自家的请求也没放过。。。

**Comment by zhenzhang20** [comment]
目前有替代方案吗？

**Comment by RIP-GitHub** [comment]
已经解决抖音的web抓取了，联系416828817

**Comment by zhangchj9** [comment]
> 已经解决抖音的web抓取了，联系416828817

单个视频抓取不需要sign和dytk，按主题或者音乐抓才是问题。

**Comment by RIP-GitHub** [comment]
> > 已经解决抖音的web抓取了，联系416828817
> 
> 单个视频抓取不需要sign和dytk，按主题或者音乐抓才是问题。

抓单个视频当然不需要，我解决的是抓某个抖音用户的所有作品

**Comment by coder-fly** [comment]
现在网页版又可以使用了，本项目代码也进行了更新，欢迎star
