### ISSUE TITLE
抖音是不是修改算法了？用你的接口什么数据都取不出啊

### ISSUE THREAD

**Issue by a5582323** [coder-fly/douyin-signature#4]
<img src="https://i.loli.net/2020/03/05/s9OQcoPZlxk2My8.png" >
代码见图

**Comment by junges521** [comment]
现在流行使用抖音手机版本了，可以联系我qq找我提供，1570207752

**Comment by skygongque** [comment]
跪求大佬更新，postman试了下接口生成的signature拿不到数据，原请求的signature可以

**Comment by suifengqjn** [comment]
这种方法不适用，最好的还是把安卓包去壳，直接去调用里面的签名方法，一劳永逸

**Comment by coder-fly** [comment]
经测试网页版算法没有改变，但是压缩算法变化了，所以在请求的时候，需要请求头中的accept-encoding更改为gzip, deflate即可正常访问。
